name: PR Manager

on:
  workflow_dispatch:
    inputs:
      branch_name:
          description: 'Enter the branch name'
          required: false
          default: ''

jobs:
  manager:
    name: Create, approve and merge

    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout on branch ${{ github.ref_name }}
        uses: actions/checkout@v4

      - name: Change file
        run: echo '-abc-' >> test.txt

      - name: Config GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git checkout -b version/${{ inputs.branch_name }}

      - name: Commit change
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add test.txt
          git commit -m "chore: version ${{ inputs.branch_name }}"
          git push version/${{ inputs.branch_name }}

      - name: Create pull request
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
          --title "version/${{ inputs.branch_name }}" \
          --body "This is an automated PR created by GitHub Actions." \
          --base main --head version/${{ inputs.branch_name }}